// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: material.sql

package db

import (
	"context"
)

const createMaterial = `-- name: CreateMaterial :one
INSERT INTO materials (
    name,
    type
)
VALUES (
    $1,
    $2
)
RETURNING
    id,
    name,
    type
`

type CreateMaterialParams struct {
	Name string       `json:"name"`
	Type MaterialType `json:"type"`
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error) {
	row := q.db.QueryRow(ctx, createMaterial, arg.Name, arg.Type)
	var i Material
	err := row.Scan(&i.ID, &i.Name, &i.Type)
	return i, err
}

const findMaterials = `-- name: FindMaterials :many
SELECT
    id,
    name,
    type
FROM materials
WHERE name ILIKE '%' || $1::text || '%' ESCAPE '\'
ORDER BY id
LIMIT $2
`

type FindMaterialsParams struct {
	Query string `json:"query"`
	Limit int64  `json:"limit"`
}

func (q *Queries) FindMaterials(ctx context.Context, arg FindMaterialsParams) ([]Material, error) {
	rows, err := q.db.Query(ctx, findMaterials, arg.Query, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Material
	for rows.Next() {
		var i Material
		if err := rows.Scan(&i.ID, &i.Name, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterial = `-- name: GetMaterial :one
SELECT
    id,
    name,
    type
FROM materials
WHERE id = $1
`

func (q *Queries) GetMaterial(ctx context.Context, id int64) (Material, error) {
	row := q.db.QueryRow(ctx, getMaterial, id)
	var i Material
	err := row.Scan(&i.ID, &i.Name, &i.Type)
	return i, err
}

const materialExists = `-- name: MaterialExists :one
SELECT EXISTS (
    SELECT 1
    FROM materials
    WHERE id = $1
)
`

func (q *Queries) MaterialExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, materialExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
