// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
)

type MaterialType string

const (
	MaterialTypeUnspecified     MaterialType = "unspecified"
	MaterialTypeRawMaterial     MaterialType = "raw_material"
	MaterialTypePackaging       MaterialType = "packaging"
	MaterialTypeSemiFinished    MaterialType = "semi_finished"
	MaterialTypeFinishedProduct MaterialType = "finished_product"
	MaterialTypeSparePart       MaterialType = "spare_part"
	MaterialTypeConsumable      MaterialType = "consumable"
)

func (e *MaterialType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaterialType(s)
	case string:
		*e = MaterialType(s)
	default:
		return fmt.Errorf("unsupported scan type for MaterialType: %T", src)
	}
	return nil
}

type NullMaterialType struct {
	MaterialType MaterialType `json:"material_type"`
	Valid        bool         `json:"valid"` // Valid is true if MaterialType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaterialType) Scan(value interface{}) error {
	if value == nil {
		ns.MaterialType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaterialType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaterialType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaterialType), nil
}

func (e MaterialType) Valid() bool {
	switch e {
	case MaterialTypeUnspecified,
		MaterialTypeRawMaterial,
		MaterialTypePackaging,
		MaterialTypeSemiFinished,
		MaterialTypeFinishedProduct,
		MaterialTypeSparePart,
		MaterialTypeConsumable:
		return true
	}
	return false
}

func AllMaterialTypeValues() []MaterialType {
	return []MaterialType{
		MaterialTypeUnspecified,
		MaterialTypeRawMaterial,
		MaterialTypePackaging,
		MaterialTypeSemiFinished,
		MaterialTypeFinishedProduct,
		MaterialTypeSparePart,
		MaterialTypeConsumable,
	}
}

type Material struct {
	ID   int64        `json:"id"`
	Name string       `json:"name"`
	Type MaterialType `json:"type"`
}

type MaterialSpec struct {
	MaterialID int64  `json:"material_id"`
	Name       string `json:"name"`
	Value      string `json:"value"`
}
