// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error)
	FindMaterials(ctx context.Context, arg FindMaterialsParams) ([]Material, error)
	GetMaterial(ctx context.Context, id int64) (Material, error)
	MaterialExists(ctx context.Context, id int64) (bool, error)
}

var _ Querier = (*Queries)(nil)
